"""Curated default topic tags offered during sign-up."""

DEFAULT_TAGS = [
    "python",
    "javascript",
    "typescript",
    "java",
    "c++",
    "c#",
    "go",
    "rust",
    "php",
    "ruby",
    "swift",
    "kotlin",
    "sql",
    "web dev",
    "frontend",
    "backend",
    "fullstack",
    "react",
    "vue",
    "node.js",
    "flask",
    "django",
    "api design",
    "databases",
    "devops",
    "docker",
    "kubernetes",
    "ci/cd",
    "linux",
    "cloud",
    "aws",
    "azure",
    "gcp",
    "ai",
    "machine learning",
    "deep learning",
    "nlp",
    "llms",
    "data science",
    "computer vision",
    "cybersecurity",
    "networking",
    "cryptography",
    "hardware",
    "iot",
    "embedded",
    "robotics",
    "game dev",
    "mobile dev",
    "git",
    "testing",
    "algorithms",
    "open source",
    "tooling",
    "digital literacy",
]
